---
name: File-SAUCE
version: 0.2
author:
  - Brian Cassidy <bricas@cpan.org>
abstract: A library to manipulate SAUCE metadata
license: perl
requires:
  Class::Accessor: 0
  FileHandle: 0
  IO::String: 1.06
  Time::Piece: 0
build_requires:
  File::Slurp: 0
  Test::More: 0
provides:
  File::SAUCE:
    file: lib/File/SAUCE.pm
    version: 0.2
generated_by: Module::Build version 0.2611
